### ISSUE TITLE
backup all database failed

### ISSUE THREAD

**Issue by xishengcai** [jarvanstack/mysqldump#6]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/21197150/230583507-49c028de-1962-46fa-b520-167c1eb4cfed.png">

**Comment by jarvanstack** [comment]
Sorry, I can't get the information about why this error happened. Can you show me the db struct and data content of this error?

**Comment by lvhaidong** [comment]
The user-defined table name is the same as the system table name, resulting in an exception；

**Comment by jarvanstack** [comment]
Solve This Problem [0.6.0](https://github.com/jarvanstack/mysqldump/releases/tag/0.6.0)
